echo "# windows-update-" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/MRnine99-jj/windows-update-.git
git push -u origin main
